#!/bin/sh

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

alias ls="ls --color=auto"
alias gu="git status -u"
alias g="git status"
alias dt="light_dark -d"
alias lt="light_dark -l"
alias inacapg="node $INACAP_PATH/index.js gabriel"
alias inacapc="node $INACAP_PATH/index.js charlotte"