#!/bin/sh

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

alias ls="ls --color=auto"
alias gu="git status -u"
alias g="git status"
alias dt="bash /home/gabriel/Programación/projects/light_dark/light_dark.sh -d"
alias lt="bash /home/gabriel/Programación/projects/light_dark/light_dark.sh -l"