[colors]
background = '#1e1e2e'
foreground = '#cdd6f4'
ansi = [
  '#45475a',
  '#f38ba8',
  '#a6e3a1',
  '#f9e2af',
  '#89b4fa',
  '#f5c2e7',
  '#94e2d5',
  '#bac2de',
]
brights = [
  '#585b70',
  '#f38ba8',
  '#a6e3a1',
  '#f9e2af',
  '#89b4fa',
  '#f5c2e7',
  '#94e2d5',
  '#a6adc8',
]

[colors.indexed]
16 = '#fab387'
17 = '#f5e0dc'

[metadata]
author = 'PinguinFrosch'
name = 'catppuccin-dark'
